name: soundpool
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 2.4.1
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  soundpool_platform_interface: ^2.2.0


flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.soundpool
        pluginClass: SoundpoolPlugin
      ios:
        pluginClass: SoundpoolPlugin
      web:
        default_package: soundpool_web
      macos:
        default_package: soundpool_macos
